[package]
name = "dataloch"
version = "0.1.0"
authors = ["Ivan Danov <idanov@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0.9.0"
